name: AFTER_MERGE
on:
  push:
    branches:
    - "main"

jobs:
  Merge_master_to_develop:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        ref: main
    - name: Checkout develop
      uses: actions/checkout@v1
      with:
        ref: develop
        clean: false
    - name: Merge master to develop and push
      run: |
        git merge --no-edit main
        git push
