name: AFTER_MERGE
on:
  push:
    branches:
    - "main"

jobs:
  Create_pull_request:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Merge master to develop and push
      run: |
        git fetch origin main
        git merge --no-edit origin/main
        git push
