name: AFTER_MERGE
on:
  push:
    branches:
    - "main"

jobs:
  Create_pull_request:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Merge master to develop and push
      run: |
        git merge --no-edit main
        git push
