name: Release Issue
on:
  issues:
    types: [closed]
jobs:
  createReleaseIssue:
    runs-on: ubuntu-latest
    outputs:
      assignee: ${{ steps.create.outputs.assignee }}
      issue: ${{ steps.create.outputs.issue }}
    steps:
    - if: contains(github.event.issue.labels.*.name, 'release')
      name: Create new Issue
      uses: bpmn-io/actions/release-issue@latest
      id: create
      with:
        template-path: 'template.md'
        package-path: 'package.json'
        moderators-path: 'moderators.json'
        labels: 'release'
  readOutputs:
    needs: createReleaseIssue
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "assignee:" ${{ needs.createReleaseIssue.outputs.assignee }}
      - run: |
          echo "issue:" ${{ fromJson(needs.createReleaseIssue.outputs.issue).number }}
