name: Release Issue
on:
  issues:
    types: [closed, assigned]
jobs:
  createReleaseIssue:
    runs-on: ubuntu-latest
    outputs:
      assignee: ${{ steps.create.outputs.assignee }}
      issue: ${{ steps.create.outputs.issue }}
    steps:
    - if: contains(github.event.issue.labels.*.name, 'release')
      name: Create new Issue
      uses: bpmn-io/actions/release-issue@latest
      id: create
      with:
        template-path: 'template.md'
        package-path: 'package.json'
        moderators-path: 'moderators.json'
        labels: 'release'
  readOutputs:
    needs: createReleaseIssue
    if: |
      always() &&
      contains(github.event.issue.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "assignee:" ${{ needs.createReleaseIssue.outputs.assignee || github.event.issue.assignee.login }}
      - run: |
          echo "issue number:" ${{ needs.createReleaseIssue.outputs.issue && fromJson(needs.createReleaseIssue.outputs.issue).number || github.event.issue.number }}
